### ISSUE TITLE
Kullanıcının yaptığı tatiller için bir model yapısının oluşturulması

### ISSUE THREAD

**Issue by cankirkgz** [cankirkgz/Travel-Guide#70]

**Comment by myavuzokumus** [comment]
Model yapısı oluşturuldu ve önceki tatiller sayfasına entegresi sağlandı.
Bitirmeden önce backend yapısıyla tam uyumluluğunda sorun çıkmaması amaçlı, user recent travels collectionunun oluşturulması bekleniyor.
